/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: "doc",
      label: "Introduction",
      id: "intro",
    },
    {
      type: "category",
      label: "Getting Started",
      items: [{ type: "autogenerated", dirName: "getting-started" }],
    },
    {
      type: "category",
      label: "Examples",
      items: [{ type: "autogenerated", dirName: "examples" }],
    },
    {
      type: "category",
      label: "Guides",
      items: [{ type: "autogenerated", dirName: "guides" }],
    },
    {
      type: "category",
      label: "Metadata",
      items: [{ type: "autogenerated", dirName: "metadata" }],
    },
    {
      type: "category",
      label: "Step Types",
      items: [{ type: "autogenerated", dirName: "step-types" }],
    },
  ],
};

export default sidebars;
